# Generated by Django 5.2.5 on 2025-09-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzurisafaris', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='blogImage',
        ),
        migrations.RenameField(
            model_name='staffmember',
            old_name='profilePicture',
            new_name='displayPicture',
        ),
    ]
