# Generated by Django 5.2.5 on 2025-10-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzurisafaris', '0002_rename_image_blogpost_blogimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(),
        ),
    ]
