"""
Django settings for uzurisafari project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m-ilax0lkgvv^40b2zkg&xnhj!)a@92xt_ux1^0327dx11v-j4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['uzurisafaris.herokuapp.com', 'localhost']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'uzurisafaris',
    'tinymce',
]

JAZZMIN_SETTINGS = {
    "site_title": "Uzuri Admin",  # Browser tab title
    "site_header": "Uzuri Administration",  # Big text at top left
    "site_brand": "Uzuri Safaris",  # Sidebar brand
    "welcome_sign": "Welcome to Uzuri Safaris Admin",  # Welcome message
    "copyright": "Uzuri Technologies © 2025",
    
    # Optional: Change logo
    "site_logo": "images/logo/uzuri-logo.png",  # Place in static/images/
    "site_logo_classes": "img-circle",  # Bootstrap classes
    "site_icon": "static/images/favicon_ico/favicon-32x32.png",  # Place in static/favicon_ico/

    "order_with_respect_to": ["uzuri_safaris.booking", "uzuri_safaris.testimonials", "uzuri_safaris.teammember", "uzuri_safaris.blogpost"],


    "custom_css": "css/custom_light.css", 

    "navigation_expanded": True,

    # App grouping in sidebar
    "show_sidebar": True,
    "related_modal_active": True,
    "icons": {
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "uzuri_safaris.booking": "fas fa-calendar-check",
        "uzuri_safaris.testimonial": "fas fa-comment-dots",
        "uzuri_safaris.staffmember": "fas fa-user-tie",
        "uzuri_safaris.department": "fas fa-building",
        "uzuri_safaris.blogpost": "fas fa-newspaper",
    },

    "side_menu": {
        "Content Management": [
            "uzuri_safaris.blogpost",
            "uzuri_safaris.testimonials",
        ],
        "Team & Clients": [
            "uzuri_safaris.teammember",
            "uzuri_safaris.booking",
        ],
    }
    
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,

    "accent": "accent-navy",  # Options: navy, blue, teal, etc.
    "navbar": "navbar-dark",  # navbar-light or navbar-dark
    "no_navbar_border": True,

    "sidebar": "sidebar-light-primary",  # dark or light
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

    "theme": "litera",  # Bootswatch theme for overall look
    "dark_mode_theme": None,  # or "darkly"
}


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uzurisafari.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uzurisafari.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'uzuridatabase',
        'USER': 'postgres',
        'PASSWORD': 'Fasilium@2025',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.environ.get('DATABASE_URL')
#     )
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (Uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    "height": 400,
    "width": "100%",
    "menubar": "file edit view insert format tools table help",
    "plugins": "lists link image table code help wordcount",
    "toolbar": "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent | link image table | removeformat | code",
    "branding": False,  # remove "Powered by TinyMCE"
}


# Email settings
# Use Gmail SMTP for sending emails
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "mehdahmedani@gmail.com"      # your Gmail
EMAIL_HOST_PASSWORD = "cstx bywg icpc vcbs "     # use App Password, not normal password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = "mehdahmedani@gmail.com"          # receiver
# Use this to send emails to the admin
# Make sure to set up App Passwords in your Google Account settings

CKEDITOR_CONFIGS = {
    'document': {
        'toolbar': [
            ['Undo', 'Redo'],
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['NumberedList', 'BulletedList', 'Blockquote'],
            ['Outdent', 'Indent'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ],
        'height': 300,
        'width': '100%',
    },
}